# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'



steps:
- script: echo Compilar y correr las pruebas unitarias v8
  displayName: 'Commit Check'

- script: |
    echo Correr las pruebas de integración
  displayName: 'Integration Tests'
