# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    echo Compilar ========================================================
    sudo apt-get update
    sudo apt-get install openjdk-8-jdk
    wget www.scala-lang.org/files/archive/scala-2.12.10.deb
    sudo dpkg -i scala*.deb
    echo "deb https://dl.bintray.com/sbt/debian/" | sudo tee -a /etc/apt/sources.list.d/sbt.list
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    sudo apt-get update
    sudo apt-get install sbt -y
    sudo apt install git
    sudo apt install which
    sudo apt-get install -y yum-utils
    sudo apt-get install docker-ce docker-ce-cli containerd.io
    sudo docker run hello-world
    sudo add-apt-repository universe
    sudo apt install alien
    sudo sbt rpm:packageBin
  displayName: 'Commit Check Phase - Fase de Verificación de COnstrucción-Compilación'

  steps:33
- script: |
    echo Test Unitario ========================================================
    sudo sbt test 
  displayName: 'Commit Check Phase - Fase de Test Unitarios'

- script: |    
    echo Copiar a Azure MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo scp -v -o StrictHostKeyChecking=no -i webserver-01_key.pem /home/vsts/work/1/s/gcs-app/target/rpm/RPMS/noarch/gcs-app-2.8.x-1.noarch.rpm azureuser@40.121.239.199:/home/azureuser
    echo Conectarse a Azure MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo ssh -tt -i webserver-01_key.pem azureuser@40.121.239.199 <<'EOT'
    echo Detener el APP y Nginx MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo systemctl stop nginx.service
    sudo systemctl stop gcs-app.service
    ls
    ls
    ls
    echo Desintalar la APP MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo rpm -e gcs-app
    echo Eliminar directorio MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo rm -rf /usr/share/gcs-app/
    echo Instalar la APP MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo rpm -i gcs-app-2.8.x-1.noarch.rpm
    echo Cambiar de usuario MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo chown -R gcs-app /usr/share/gcs-app/
    sudo chgrp -R gcs-app /usr/share/gcs-app/
    logout
    EOT
    sudo scp -v -o StrictHostKeyChecking=no -i webserver-01_key.pem nginx.conf azureuser@40.121.239.199:/etc/nginx
    echo Volver a conectarse a Azure MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo ssh -tt -i webserver-01_key.pem azureuser@40.121.239.199 <<'EOT'
    echo Reiniciar el APP y nginx MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo systemctl restart nginx.service
    sudo systemctl restart gcs-app.service
    echo Habilitar el demonio MENSAJEEEEEEEEEEEEEEEEEEEE
    sudo setsebool -P httpd_can_network_connect on
    logout
    EOT
    echo FIN MENSAJEEEEEEEEEEEEEEEEEEEE16
  displayName: 'Integration Tests'